### PR TITLE
Jukebox song updates

### PR DESCRIPTION
**Pull request by arty01238**
### Description

New Songs And Files Updated To Current Main Branch Layout

### Readiness Checklist
- [x] I have run `make format` to format the changes
- [x] I have compiled the firmware and the changes have no warnings
- [x] I have compiled the emulator and the changes have no warnings
- [x] I have run `make cppcheck` and checked that `cppcheck_result.txt` has no warnings for the changes
- [x] I have added doxygen comments to any code used by more than one Swadge mode. This includes `/*! \file` comments with Design Philosophy, Usage, and Example sections for new headers.
- [x] I have run `make docs` and checked that `doxy_warnings.txt` has no warnings for the new code

### CODE REVIEW

**Review by AEFeinstein — APPROVED** [review]

**Comment by AEFeinstein** [comment]
@arty01238 seems good to me so far. LMK when this goes from WIP to ready to merge.

**Comment by Brycey92** [comment]
Will be ready in a few minutes here, just got the last of the fixed files

**Comment by arty01238** [comment]
@AEFeinstein Its ready to pull! All checks pass!

**Review by Brycey92 — APPROVED** [review]

**Review by AEFeinstein — APPROVED** [review]
Still looks good to me. While I appreciate the project-wide autoformat, it's better practice to only update the things you're working on and leave other people's stuff be. I was planning on doing that format after everything was merged anyway.

**Comment by Brycey92** [comment]
I took a look at the project-wide format, and it needs a few `//clang-format off` sprinkled in

**Comment by AEFeinstein** [comment]
You are likely right, though I'd leave that as an exercise to individual authors.

**Pull request merged**
